#!/bin/bash

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-namely}
ALPINE_VERSION=${ALPINE_VERSION:-3.9}
GRPC_VERSION=${GRPC_VERSION:-v1.15.1}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-v1.15.1}
BUILD_VERSION=${BUILD_VERSION:-0}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}
BUILDS=("protoc-all" "protoc" "prototool" "grpc-cli" "gen-grpc-gateway")
