
# build the image on PRs and master

name: PR

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_HASH: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: nelonoel/branch-name@v1.0.1

      - name: Docker Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

      - name: Create Build Version
        id: build_version
        if: success()
        run: |
          echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)

      - name: Build
        if: success()
        env:
          BUILD_VERSION: ${{ steps.version.outputs.SHA_SHORT }}
        run: make build
